language: java

sudo:     false

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer  

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
